version: "2"

services:
    mongo:
        image: mongo

    server:
        build: ./server
        depends_on:
            - mongo
        links:
            - mongo
        volumes:
            - ./server:/app
        ports:
            - "80:3000"
        restart: always